/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Time;
import Controlador.Controlador;
import Modelo.Cocina;
import Modelo.Mesa;
import Modelo.Mesero;
import Modelo.Pedido;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sony
 */
public class CocinaView extends javax.swing.JFrame implements Runnable{
    private int seg = 0;
    private int min = 0;
    private int hora = 0;
    private int NumVentas=0;
    private boolean continuar = true;
    private Time i;
    Controlador controlador;
    Pedido p;
    Cocina cocinaClass;

    public void setCocinaClass(Cocina cocinaClass) {
        this.cocinaClass = cocinaClass;
    }
    
    public JTable getTablaCocina() {
        return tablaCocina;
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }
    
    /**
     * Creates new form CocinaView
     */
    public CocinaView() {
        initComponents();
         this.setLocation(10,160);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCocina = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnCocinar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        TextSeg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaCocina.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        tablaCocina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.Pedidio", "No.Mesa", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tablaCocina);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 290, 275));

        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setText("Info.Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 150, -1));

        btnCocinar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnCocinar.setText("Cocinar");
        btnCocinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocinarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCocinar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 150, -1));

        jButton3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 260, 140, 30));

        jButton4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton4.setText("Ver Pedidos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 150, -1));

        TextSeg.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        TextSeg.setForeground(new java.awt.Color(255, 255, 255));
        TextSeg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextSeg.setText("0");
        getContentPane().add(TextSeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 90, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dinner.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 70, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Kitchen.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        controlador.verPedidosCocina(cocinaClass);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnCocinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocinarActionPerformed
        if (tablaCocina.getSelectedRow()!=-1) {
//            int row = tablaCocina.getSelectedRow();
            int row = 0;
            String NoPedido = tablaCocina.getValueAt(row, 0).toString();
            Pedido p = controlador.actualizarStock(tablaCocina.getValueAt(row, 0).toString());
            System.out.println(p);
            if (p!=null) {
                controlador.findPedido(NoPedido).setProductos(p.getProductos());            
                Pedido pd = new Pedido(p.NroPedido,p.Mesa,p.Camarero,p.getProductos(),p.getProductos().getTamano());
                pd.addPrice(""+p.getValor());
                Mesero mesero = controlador.findMesero(p.Camarero);
                System.out.println("pd price: " + p.getValor());
                mesero.sumTotalVendido(p.getValor());
                System.out.println("totalvendidomeserococin: " + mesero.getTotalVendido());
                mesero.addNumVentas(1);
                this.NumVentas++;
                controlador.addPedidoToMesa(pd);
                continuar = true;
                btnCocinar.setEnabled(false);
                resetSeg();
                i = null;            
                int timeXproductos = p.getLista().getTamano();
                timeXproductos = timeXproductos * 3;            
                System.out.println(timeXproductos);
    //            controlador.verPedidosCocina(cocinaClass);
                i = new Time(this,timeXproductos);
                i.start();
            }else{
                DefaultTableModel model = (DefaultTableModel) tablaCocina.getModel();  
                System.out.println("Pedido NO REALIZADO");    
                controlador.eliminarPedidoCocina(NoPedido);
                model.removeRow(row);
                
            }
            
        }
    }//GEN-LAST:event_btnCocinarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tablaCocina.getSelectedRow()!=-1) {
            int row = tablaCocina.getSelectedRow();
            System.out.println(tablaCocina.getValueAt(row, 0).toString());            
            Pedido p = controlador.findPedido(tablaCocina.getValueAt(row, 0).toString());            
    //        p.showPedidoList();
            String productosTxt = p.getProductosTxt();
                JOptionPane.showMessageDialog(this,
                    "No.Pedido: " + tablaCocina.getValueAt(row, 0).toString()
                    +"\nNo.Mesero:" + p.getCamarero()
                    + "\nNo.Mesa: " + tablaCocina.getValueAt(row, 1).toString()
                    + "\n----------\n" + productosTxt);            
        }     
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CocinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CocinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CocinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CocinaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CocinaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextSeg;
    private javax.swing.JButton btnCocinar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCocina;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {

    }
    public synchronized int aumentSeg() {
        seg++;
        TextSeg.setText(String.valueOf(seg));
        return seg;
    }

    public synchronized int getSeg() {
        return seg;
    }

    public void resetSeg() {
        TextSeg.setText(String.valueOf("0"));
        seg = 0;
    }

    public synchronized boolean isContinuar() {
        return continuar;
    }

    public synchronized void seguir() {
        continuar = true;
    }

    public synchronized void parar() {
        btnCocinar.setEnabled(true);
        continuar = false;        
        DefaultTableModel model = (DefaultTableModel) tablaCocina.getModel();  
//        int row = tablaCocina.getSelectedRow();                  
        int row =0;                  
        String NoPedido = tablaCocina.getValueAt(row, 0).toString();       
        controlador.eliminarPedidoCocina(NoPedido);
        model.removeRow(row);
        
        
    }
}
