/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import Modelo.ListaPedido;
import Modelo.Mesa;
import Modelo.Mesero;
import Modelo.Pedido;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sony
 */
public class MesasView extends javax.swing.JFrame {

    Controlador controlador;

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    /**
     * Creates new form MesasView
     */
    public MesasView() {
        initComponents();
        this.setLocation(100, 400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMesas = new javax.swing.JTable();
        mesaID = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        Btn_FacturaMesa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Btn_Fact = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        tablaMesas.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        tablaMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.Pedido", "Mesero ID"
            }
        ));
        jScrollPane1.setViewportView(tablaMesas);

        mesaID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        mesaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesaIDActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mesa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(mesaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mesaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 230));

        jPanel5.setBackground(new java.awt.Color(0, 191, 118));

        jButton4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton4.setText("Actualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Btn_FacturaMesa.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Btn_FacturaMesa.setText("Factura / Mesa");
        Btn_FacturaMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_FacturaMesaActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setText("Info.Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Btn_Fact.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Btn_Fact.setText("Pedir factura");
        Btn_Fact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_FactActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Btn_FacturaMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Fact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_FacturaMesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Fact)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 190, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tablaMesas.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            model.removeRow(i);
            i = -1;
        }
        Mesa mesa = controlador.findMesa(mesaID.getSelectedItem().toString());
        System.out.println("!!!!");
        mesa.getPedidos().showList();
        System.out.println("!!!");
        controlador.actualizarTablaMesasView(tablaMesas, mesa, mesaID.getSelectedItem().toString());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tablaMesas.getSelectedRow() != -1) {
            int row = tablaMesas.getSelectedRow();
            System.out.println(tablaMesas.getValueAt(row, 0).toString());
            Mesa m = controlador.findMesa(mesaID.getSelectedItem().toString());
            Pedido p = m.getPedidos().findPedido(tablaMesas.getValueAt(row, 0).toString());
            p.showPedidoList();
            String productosTxt = p.getProductosTxt();
            JOptionPane.showMessageDialog(this,
                    "No.Pedido: " + tablaMesas.getValueAt(row, 0).toString()
                    + "\nNo.Mesero:" + p.getCamarero()
                    + "\nNo.Mesa: " + tablaMesas.getValueAt(row, 1).toString()
                    + "\n----------\n" + productosTxt);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Btn_FactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_FactActionPerformed
        DefaultTableModel model = (DefaultTableModel) tablaMesas.getModel();
        if (model.getRowCount() != 0) {
            int row = tablaMesas.getSelectedRow();
            int NroPedido = Integer.parseInt(tablaMesas.getValueAt(row, 0).toString());
            String ID = mesaID.getSelectedItem().toString();
            String Factura = "";
            Factura = controlador.getFactura(NroPedido, Factura, ID);
            JOptionPane.showMessageDialog(null, Factura);
            model.removeRow(tablaMesas.getSelectedRow());
            Mesa mesa = controlador.findMesa(ID);
            mesa.getPedidos().eliminarPedido(mesa.getPedidos().findPedido(NroPedido + ""));
        }

//        tablaMesas.setModel(model);
    }//GEN-LAST:event_Btn_FactActionPerformed

    private void Btn_FacturaMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_FacturaMesaActionPerformed
        DefaultTableModel model = (DefaultTableModel) tablaMesas.getModel();
        if (model.getRowCount() != 0) {
            String ID = mesaID.getSelectedItem().toString();
            String Factura = "";
            Mesa mesa = controlador.findMesa(ID);
            String pedidos = "";
            int cont = 0;
            Mesero mesero = controlador.findMesero(tablaMesas.getValueAt(0, 1).toString());
            for (int i = 0; i < tablaMesas.getRowCount(); i++) {
                int NroPedido = Integer.parseInt(tablaMesas.getValueAt(i, 0).toString());
                Pedido p = mesa.getPedidos().findPedido(NroPedido + "");
                pedidos = pedidos + controlador.getFacturaT(p) + "\n";
                Factura = Factura + controlador.getValorPedido(NroPedido, Factura, ID);
                cont = cont + Integer.parseInt(Factura);
                mesa.getPedidos().eliminarPedido(mesa.getPedidos().findPedido(NroPedido + ""));
            }

            mesa.setMesero(null);
            mesero.getMesas().showList();
            mesero.getMesas().eliminarMesa(mesa);
            System.out.println(mesa.getMesero());

            Factura = "Productos: \n" + pedidos + "Precio Base: " + "................" + "$" + cont + "\n";
            Factura = Factura + "IVA 5%" + "............" + (cont * 0.05) + "$" + "\n";
            Factura = Factura + "Propina 10%" + "........." + (cont * 0.1) + "$" + "\n";
            Factura = Factura + "Total a Pagar" + "............" + (cont + (cont * 0.05 + cont * 0.1)) + "$" + "\n";
            Factura = Factura + ".................................................";
            System.out.println("a" + Factura + "a");
            JOptionPane.showMessageDialog(null, Factura);
            for (int i = 0; i < model.getRowCount(); i++) {

                model.removeRow(i);
                i = -1;
            }
        }


    }//GEN-LAST:event_Btn_FacturaMesaActionPerformed

    private void mesaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesaIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesaIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MesasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MesasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MesasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MesasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MesasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Fact;
    private javax.swing.JButton Btn_FacturaMesa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> mesaID;
    private javax.swing.JTable tablaMesas;
    // End of variables declaration//GEN-END:variables
}
